import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import React from "react";
import {AuthProvider} from "@/components/context/AuthContext";
// import ScrollWrapper from "@/components/ScrollBar/ScrollWrapper";
import SmoothScroll from "@/components/ScrollBar/SmoothScroll";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AuthProvider>
            {/*<ScrollWrapper>*/}
            {/*  <Header />*/}
            {/*  {children}*/}
            {/*</ScrollWrapper>*/}

            <SmoothScroll>
                <Header/>
                {children}
            </SmoothScroll>
        </AuthProvider>
        </body>
        </html>
    );
}
