import type {Metadata} from "next";
// import {Rubik} from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import React from "react";
import {AuthProvider} from "@/components/context/AuthContext";
import FootCondition from '@/components/ConditionalFooter/page'

// const Rubik_mono = Rubik({
//     variable: "--font-rubik-mono",
//     subsets: ["latin"],
//     weight: ["400", "500", "600", "700"],
//     display: "swap",
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ru">
        <head>
            <link
                rel="preload"
                href="/fonts/Rubik-Regular.ttf"
                as="font"
                type="font/ttf"
                crossOrigin="anonymous"
            />
            <link
                rel="preload"
                href="/fonts/Rubik-Light.ttf"
                as="font"
                type="font/ttf"
                crossOrigin="anonymous"
            />
        </head>
        <body
            className={`antialiased min-h-screen flex flex-col`}
        >
        <AuthProvider>
            <Header/>
            <main className="flex-grow">
                {children}
            </main>
            <FootCondition/>
        </AuthProvider>
        </body>
        </html>
    );
}
